export interface Challenge {
  id: string;
  title: string;
  description: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  tags: string[];
  longDescription?: string; // For the individual challenge page
  templateCode?: string; // Starter code for the editor
  // Add more fields like constraints, examples, test cases later
}

export const mockChallenges: Challenge[] = [
  {
    id: 'reverse-string-ai',
    title: 'Reverse a String (AI Twist)',
    description: 'Write a function that reverses a string, but the string might contain special AI-generated characters.',
    difficulty: 'Easy',
    tags: ['string', 'array', 'AI parsing'],
    longDescription: 'Your task is to reverse a given string. However, this string isn\'t just any string; it may include special characters or sequences generated by an AI model (e.g., <|marker|> or ##value##). These special sequences should be treated as single units and their internal order must be preserved when reversing. For example, if an AI marker is `##123##`, it should remain `##123##` after reversal, not `##321##`. The overall order of these units and regular characters should be reversed.\n\nExample:\nInput: "hello <|world|> ##123##"\nOutput: "##123## <|world|> hello"'
  },
  {
    id: 'image-classifier-confidence',
    title: 'AI Image Classifier Confidence',
    description: 'Given a list of AI image classifier outputs, filter those above a confidence threshold.',
    difficulty: 'Easy',
    tags: ['data processing', 'AI', 'filtering'],
    longDescription: 'You are given an array of objects, where each object represents an AI image classifier\'s prediction for an image. Each object has the structure: `{ label: string, confidence: number }`. Write a function that takes this array and a confidence threshold (a float between 0 and 1) and returns a new array containing only the predictions where the confidence score is greater than or equal to the threshold. The order of the filtered predictions should be maintained.'
  },
  {
    id: 'nlp-sentiment-analyzer',
    title: 'Basic NLP Sentiment Analyzer',
    description: 'Implement a simple sentiment analyzer for short text snippets based on a keyword list.',
    difficulty: 'Medium',
    tags: ['NLP', 'text processing', 'AI', 'keywords'],
  },
  {
    id: 'ai-pathfinding-grid',
    title: 'AI Agent Pathfinding on Grid',
    description: 'Find the shortest path for an AI agent on a 2D grid with obstacles.',
    difficulty: 'Hard',
    tags: ['pathfinding', 'AI agent', 'grid', 'BFS', 'DFS'],
  },
];

export const getChallengeById = (id: string): Challenge | undefined => {
  return mockChallenges.find(challenge => challenge.id === id);
};